"""Initial migration.

Revision ID: 8b3f08047de1
Revises: 
Create Date: 2025-03-06 01:35:22.853577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b3f08047de1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_users', schema=None) as batch_op:
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('phone_verification_sent_at')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('email_verification_sent_at')
        batch_op.drop_column('last_failed_login')
        batch_op.drop_column('phone_verification_code')
        batch_op.drop_column('password_changed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_changed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_verification_code', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_failed_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_verification_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_verification_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_verification_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
