"""empty message

Revision ID: f4079f9efbaf
Revises: 15f5422a4379
Create Date: 2025-03-06 01:52:37.746363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4079f9efbaf'
down_revision = '15f5422a4379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
